### ISSUE TITLE
binder and yaml update

### ISSUE THREAD

**Issue by nbreznau** [nbreznau/CRI#4]
@nuest I have updated some RMD files and of course we now have very new versions of R and all packages. I can knit all parts together myself but the GitHub server fails. I assume this is because we need to also update the yaml and binder info? Can you assist please?

**Comment by nbreznau** [comment]
I realized that runtime.txt needs to have the version of R that I am running locally, no? So i changed it to reflect this, but it still doesn't knit after pushing.

**Comment by nbreznau** [comment]
Still not working, error is "failed to install 'insight' from GitHub", but 'insight' is an R package...

**Comment by nbreznau** [comment]
Issue resolved. It didn't like remotes::install_github, but those two packages were part of CRAN so i just gave them a regular R install.

**Comment by nuest** [comment]
Great to see you could fix this @nbreznau I am on parental leave until spring, so please reach out repeatedly via email if I can help in the future, GH notifications are impossible to handle right now.

Also, good fix it it works. I likely installed selected packages with remotes because the version available from the freezed CRAN in tue container might have been too old.
